version: '3.8'

services:
 app:
  build: .
  ports:
    - "8080:8080"
  depends_on:
    db:
      condition: service_healthy
  environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASSWORD=password
    - DB_NAME=postgres

 db:
  image: postgres:alpine
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: postgres
  volumes:
    - postgres-db:/var/lib/postgresql/data
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 5s
    timeout: 5s
    retries: 5

volumes:
  postgres-db:
